### ISSUE TITLE
How do we set the CORS headers on the icecast2 server? 

### ISSUE THREAD

**Issue by dzhen19** [eshaz/icecast-metadata-js#103]
Hey @eshaz! This isn't really a problem relating to the library but how do you set up the Access-Control-Allow-Headers on the icecast server? 

Thanks!

**Comment by eshaz** [comment]
You can add the CORS headers to Icecast by modifying the your server's configuration file. It's described here in the documentation for Icecast: https://www.icecast.org/docs/icecast-trunk/config_file/#http-headers

If you want ICY metadata, you'll also need to add the headers described here in the docs for this library: https://github.com/eshaz/icecast-metadata-js#cors

**Comment by GuanyunLu** [comment]
Oooh! I'm terribly sorry, I forgot to add the port number in the audio source, so I got 404 all the time. It was my own fault.😂Thank you again for your patience and instructions! Have a good day(or night)!
