### ISSUE TITLE
Change source after stopping?

### ISSUE THREAD

**Issue by karolyi** [eshaz/icecast-metadata-js#105]
Hi,

thank you for this module, it's great! I'm building for myself a little web player with multiple channels, and I wondered if there is a way to stop the player, change its source (the URL it plays), and then start playing the other source?

I was looking for a function or a property but no avail so far.

What's your advice on this? Thanks in advance.

**Comment by BajakiGabesz** [comment]
Hi @karolyi,

I think @eshaz can answer this question better, but I was in the same shoes.
I could solve it by making the player object static and call stop before I started another source. It is working perfectly.

The next code is used in React, but it may help:
`
let streamPlayer: IcecastMetadataPlayer | undefined = undefined;

const playAsync = async (url: string): Promise<void> => {
    streamPlayer = new IcecastMetadataPlayer(
        url
    );
    await streamPlayer.play();
}

const stop = (): void => {
    await streamPlayer?.stop();
    await streamPlayer?.detachAudioElement();
}
`

Hope this helps.

**Comment by karolyi** [comment]
The code is a bit garbled to me but if I understand it right, you basically instantiate a new player whenever you want to play another source? If that's the case, why do you need to detach the audio element?

**Comment by karolyi** [comment]
It says that `detachAudioElement` is only necessary if you've passed your own audio element for use with the player.

I'm assuming some former version of your code had it?

**Comment by BajakiGabesz** [comment]
I just tried to copy the code and remove all the unnecessary parts, but with less success. I also use HTMLAudioElement and detachAudioElement was needed for other kinds of purposes.
Anyhow, if you only need to stop the audio, switch the URL and start, you may try to switch it by changing the underlying audio element source:
`streamPlayer.audioElement.src = ""`

**Comment by karolyi** [comment]
>  Anyhow, if you only need to stop the audio, switch the URL and start, you may try to switch it by changing the underlying audio element source:
> `streamPlayer.audioElement.src = ""`

I was looking into that too, but the audio element has an internal blob source (possibly coming from the decoder part of the player) as a source, and with changing that to the URL you'd lose the metadata decoding ability.

**Comment by BajakiGabesz** [comment]
Probably, that is another reason I was made my solution as it is, but I also play regular audio files by using my own audio element, not just streams.
So, maybe I could not give you better advice at this moment than recreate the IcecastMetadataPlayer object, but maybe the creator of this plugin could give better hints.

**Comment by karolyi** [comment]
Thanks for the advice anyway. I'm suspecting that your solution (instantiating another player) will be the one here, but let's wait for @eshaz's response too.

**Comment by eshaz** [comment]
> you basically instantiate a new player whenever you want to play another source? 

Yes, to change the source you need to create a new instance with the new endpoint passed into the constructor. Once the instance is constructed, there's intentionally no way to change the source URL. There is internal state in the player that is set up when the first call to `play()` happens that makes it impossible to change the source URL in the current design. Changing the audio element source won't work and might cause unexpected behavior / errors.

> It says that `detachAudioElement` is only necessary if you've passed your own audio element for use with the player.

Yes, this is correct. This method is only needed when you want to reuse your audio element for something else after your done with the `IcecastMetadataPlayer` instance.

Here's a [code example](https://github.com/eshaz/icecast-metadata-js/blob/1b450436eded80bb97533a97724073aebada8aa8/src/demo/public/demo.html#L1223) in the demo for this project that does this. After you've called `stop()` on your instance, you can create a new instance with the new URL, call `play()`, and let the old instance be garbage collected.

**Comment by karolyi** [comment]
Thanks for your response reinforcing my thoughts! Closing this issue.
