### ISSUE TITLE
Volume control?

### ISSUE THREAD

**Issue by anonwins** [eshaz/icecast-metadata-js#118]
Hello, this is a great tool and thank you very much. I use it in my stations.

Is there any way to get/set the volume of the player?

**Comment by eshaz** [comment]
Yes, you can control the volume using the audio element controls. See: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

```js
const player = new IcecastMetadataPlayer("https://example.com/stream");

player.audioElement.volume = 0.5; // get the audio element attached to the player and set volume to 50%
```
