### ISSUE TITLE
Sometimes the audio starts to lag behind on the stream

### ISSUE THREAD

**Issue by jonathandv** [eshaz/icecast-metadata-js#130]
In IcecastMetadataPlayer sometimes the audio is not in sync anymore with the stream, and the gap becomes larger over time.

It happens randomly but I've experienced it a few times on Chrome (windows). I don't know if it's related to the browser (I can figure that out with some more testing). In my app I measure the time difference between where the stream (the icecast server) is at and where IcecastMetadataPlayer is at. I listen to the audio with my ears, but more precisely, I record the moment the metadata event is fired, indicating the start of a new song. Over time the time difference with the stream slowly increases and can reach a gap of 1 minute after an hour of playing, meaning the audio is 1 minute behind on the actual stream.

My personal app relies on the switching of songs (ad hoc) and it is important that the audio for every listener to the stream is somewhat in sync (within 10 seconds precision). But some listeners might be out of sync considerably. I've tested with 2 devices side by side. The issue can be fixed by restarting (re-instantiating) the IcecastMetadataPlayer.

I will implement a workaround that will stop-start the audio (or reinstantiate the player object) when the gap becomes more than 10 seconds, but it will not be a smooth transition for the listener. I'm hoping there's a better solution.

The gap never decreases after it has increased (the audio doesn't catch up), but it would be nice if there was a catch-up mechanism. A somewhat smooth re-sync mechanism.

Hopefully this explains the issue well. Let me know if I can provide more info.

**Comment by eshaz** [comment]
I don't think there is anything in IcecastMetadataPlayer that would cause this. What's probably happening is that each listener's audio is playing at different rates that, while not noticeable to the ear, eventually accumulate to cause significant differences after playing for long durations. IcecastMetadataPlayer has a few different playback methods for compatibility reasons, but they all rely on the client to playback the audio using the interfaces provided in a browser (MediaSource, Web Audio, and HTML5 audio element).

You might try running tests for each [`playbackMethod`](https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-player#options)
to see if that changes anything. Depending on your browser and OS, one of these web interfaces could be better than the other for playing the audio consistently.

You might also try a test where you play your stream on two different devices that you know have had this issue and record the output. Then you could align these recordings in Audacity and see if there's any consistency to how audio becomes out of sync between devices.

Finally, there is the `onCodecUpdate` callback that is triggered with codec information parsed from the compressed audio while the stream is playing. The duration fields in there are sample accurate and garenteed to be correct. You can check to see if playback starts to drift over time based on this.

Other that stopping and starting playback in your app when you think the audio is out of sync, at this point I can't think of anything that should be done in IcecastMetadataPlayer to fix the client's audio playback rate, unless you find a bug somewhere in the playback methods that is causing the audio to drift.

**Comment by jonathandv** [comment]
Thank you for a great answer :) Setting the preferred playback method to 'webaudio' seems to solve the problem. I tested on iOS Safari and Windows Chrome. Previously, in both those browsers 'mediasource' was chosen by default (if no preferred method was provided), but only in Windows Chrome it seems (on my computer) a delay would build up often. Now those browsers will use 'webaudio' and things seem fine in Windows Chrome, but I have to test a bit more to be sure.

It's interesting to learn about these things. The media source documentation says it's experimental technology, so as long as the stream type is supported, it might be best to use webaudio anyway.

I'll keep a resync/restart mechanism in my app, just in case.

I suppose you can close this issue, and keep it around as information, in case someone experiences the same thing.
