### ISSUE TITLE
iOS 10, 12 and 13 playbackMethod error.

### ISSUE THREAD

**Issue by vseverikov** [eshaz/icecast-metadata-js#136]
On these versions of iOS, the webaudio and html5 method mainly works. If you set an endpoint with the received audio/aac data, then webaudio will be selected in player.js:94, and it does not have aac support in the mapping, because of this, the HTML5 player is eventually selected, because of this an error occurs.

Also on version 10 of iOS, icecastMetadataPlayer.js:55 is checked against window.EventTarget, but somehow it doesn’t work like that. Because of this, errors occur and the player crashes. I solved it by overriding window.EventTarget with a polyfill.

**Comment by eshaz** [comment]
I was able to reproduce the `EventTarget` issue, which I'll have a fix out for shortly.

As for AAC support, if it is not listed in the mapping, then your browser's `Audio` element cannot play back that format. HTML5 playback support for a format is determined by checking the `Audio` element `canPlayType()` method [here](https://github.com/eshaz/icecast-metadata-js/blob/382741cf40f4f92c4f7bcf635e9ab03970697f7c/src/icecast-metadata-player/src/players/HTML5Player.js#L19-L23). Support varies depending on your platform and browser. I would think iOS would have AAC support pre-installed, but that might not be the case for all versions / regions. There's nothing that can be done in this library to add AAC support to the Audio element if your browser doesn't support it.

Could you post a screenshot of what you see here in the [supported codecs section](https://eshaz.github.io/icecast-metadata-js/demo.html#supported-codecs)?

**Comment by Camelot22rus** [comment]
> I was able to reproduce the `EventTarget` issue, which I'll have a fix out for shortly.
> 
> As for AAC support, if it is not listed in the mapping, then your browser's `Audio` element cannot play back that format. HTML5 playback support for a format is determined by checking the `Audio` element `canPlayType()` method [here](https://github.com/eshaz/icecast-metadata-js/blob/382741cf40f4f92c4f7bcf635e9ab03970697f7c/src/icecast-metadata-player/src/players/HTML5Player.js#L19-L23). Support varies depending on your platform and browser. I would think iOS would have AAC support pre-installed, but that might not be the case for all versions / regions. There's nothing that can be done in this library to add AAC support to the Audio element if your browser doesn't support it.
> 
> Could you post a screenshot of what you see here in the [supported codecs section](https://eshaz.github.io/icecast-metadata-js/demo.html#supported-codecs)?

Our radio responds in aac format, which is not supported in the canPlayType function of WebAudioPlayer.js, but in the Player.js:86 file, it checks not from canPlayType, but from supportedSources, which has WebAudioPlayer. As a result, in this function, WebAudio works for us, but in fact html5 player
