### ISSUE TITLE
New Station: London JazzFM

### ISSUE THREAD

**Issue by lexterror** [eshaz/icecast-metadata-js#137]
Thank you for your work!

Check out this station url:

http://edge-bauerall-01-gos2.sharp-stream.com/jazz.aac?aw_0_1st.skey=1654628438&aw_0_1st.playerid=BMUK_RPi

Also, on Android theres an app called netkeeper that is able to get any url for any radio station playing in any browser/app!

Thank you!

**Comment by eshaz** [comment]
Nice station!

I tried this in the demo and also found the https endpoints and a mp3 stream through trial and error. These both work with ICY metadata.

* AAC HTTPS: https://edge-bauerall-01-gos2.sharp-stream.com/jazz.aac
* MP3 HTTPS: https://edge-bauerall-01-gos2.sharp-stream.com/jazz.mp3

You might also check out the [Xiph station directory](https://dir.xiph.org/) for more stations.

**Comment by lexterror** [comment]
This is the 128kbps stream of the same station!

http://edge-bauerall-01-gos2.sharp-stream.com/jazz.mp3?aw_0_1st.skey=1654628523&aw_0_1st.playerid=BMUK_RPi

https://media.info/radio/stations/jazz-fm/listen

http://lsn.to/JAZ

Thank you!

Thank you!
