### ISSUE TITLE
Legacy support

### ISSUE THREAD

**Issue by lollita** [eshaz/icecast-metadata-js#141]
Do you can add a option for browser that not support Regex-Groups and Exponentiation (**) ?

**Comment by eshaz** [comment]
Which module are you asking for: `icecast-metadata-player`, `icecast-metadata-js`, or `icecast-metadata-stats`?

**Comment by lollita** [comment]
I'm trying icecast-metadata-player-1.13.1.min.js

**Comment by eshaz** [comment]
Which browser / version are you using?

Generally, I aim for compatibility with the latest standards that are implemented across the latest versions of all browsers. In `icecast-metadata-player`, there is a lot of modern Javascript functionality that's core to the library's functionality, such as `MediaSource`, and `WebAssembly` that may not be compatible with browsers that don't support regex groups and the exponentiation operator.

You're welcome to experiment with the [webpack settings ](https://github.com/eshaz/icecast-metadata-js/blob/1dfbfcef639fec76166a4c71b79e22a8e6ab339d/src/icecast-metadata-player/webpack.config.js) to create a build that polyfills the regex groups and exponentiation.

[Documentation for webpack](https://webpack.js.org/configuration/target/)

**Comment by lollita** [comment]
Abandon legacy: also ReadableStream is not supported.
