### ISSUE TITLE
Fetch currentsong differences

### ISSUE THREAD

**Issue by lollita** [eshaz/icecast-metadata-js#142]
What differences are there between using this library and fetch "/currentsong?sid=#" ?

**Comment by eshaz** [comment]
I'm not sure what that endpoint is. Can you explain more about what you're asking?

**Comment by lollita** [comment]
Read [here](https://stackoverflow.com/questions/43234467/how-to-get-shoutcast-current-track-title-and-artwork-in-js).

**Comment by eshaz** [comment]
`icecast-metadata-player` reads the metadata that is embedded in the stream request (either ICY or Ogg), vs. your fetch request example that polls another endpoint for the metadata. There are a few downsides to polling where there is more network traffic and the metadata is not synchronized fully with the audio. Polling might be good enough for some usecases though.

Also this library enables broader playback support for audio codecs with a few builtin decoders (i.e. iOS support) and has retry logic and stream switching logic built in.

See the [readme](https://github.com/eshaz/icecast-metadata-js/blob/1dfbfcef639fec76166a4c71b79e22a8e6ab339d/src/icecast-metadata-player/README.md) for a more detailed description of these features.

I would suggest consulting the docs first and see if that answers your question before opening an issue. Please open an issue though if something in the docs is missing or unclear.
