### ISSUE TITLE
Error while trying to use library with Rollup

### ISSUE THREAD

**Issue by isiah-lloyd** [eshaz/icecast-metadata-js#149]
Tried testing this library using Rollup and this [starter project](https://github.com/rollup/rollup-starter-app). First ran into issue #148, after manually adding IcecastReadableStream to the exports, I get the following informational messages while building: 
![image](https://user-images.githubusercontent.com/885544/204159927-3f9abd20-c37f-4883-9746-533971c73f33.png)

And when attempting to load in the browser: 
![image](https://user-images.githubusercontent.com/885544/204159951-49a92699-438a-4a3f-93f1-8e3a5d333d4a.png)

**Comment by eshaz** [comment]
It looks like you need to configure rollup to use the browser version. There is a NodeJS and browser version of this library, and the error your getting is from the NodeJS specific files that should not be used in a browser environment.

Here's where the browser version is exported. https://github.com/eshaz/icecast-metadata-js/blob/1dfbfcef639fec76166a4c71b79e22a8e6ab339d/src/icecast-metadata-js/package.json#L15

If you find some documentation for rollup to use the browser dependency, please post it here so this can help others in the future.

**Comment by eshaz** [comment]
I just want to follow up and see how this is going. Did my suggestion above help?

**Comment by isiah-lloyd** [comment]
@eshaz hey there! thanks for following up! been a bit busy but definitely want to get this library working for my [Steam Deck radio player](https://github.com/isiah-lloyd/radiyo-steam-deck). 

I treid using the `{browser: true}` option for the resolve rollup plugin and it fixes #148 (I assume that means it's now using the `browser.js` entry point instead of `index`. But I still get the above errors when trying to build the rollup starter project with this library.

**Comment by eshaz** [comment]
Ok, I found the problem. I'm using the [`web-worker`](https://github.com/developit/web-worker) library to implement the Worker api in a Node JS environment in a few of my other dependencies used by `icecast-metadata-player`. Unfortunately, this block in their package.json

https://github.com/developit/web-worker/blob/29fef9775702c91887d3d8733e595edf1a188f31/package.json#L7-L11

is not compatible with the rollup-resolve `{browser: true}` option.

https://github.com/rollup/plugins/blob/7b6255774053ef170d9302cbbd8f99d5a58485ed/packages/node-resolve/README.md?plain=1#L64-L71

I'll work on getting a fix released here soon.

**Comment by eshaz** [comment]
I've just released icecast-metadata-player/1.13.2. This should fix the error you were getting. Let me know how it goes!

**Comment by isiah-lloyd** [comment]
@eshaz It's working now! Thanks.
