### ISSUE TITLE
Multiple Stream Endpoints

### ISSUE THREAD

**Issue by eshaz** [eshaz/icecast-metadata-js#150]
Some streaming setups have multiple servers that provide identical streams for load balancing and failover. IcecastMetadataPlayer could utilize these by allowing an array of endpoints to be set on instantiation and then selecting which one to use for playback. When a failure occurs, IcecastMetadataPlayer would then cycle through the endpoints until a successful request is made.

- [ ] Add option to pass in multiple source endpoints on instantiation
- [ ] Add option to randomize or use ordered selection of stream endpoint
- [ ] Failover to next random endpoint when there is a failure or timeout
- [ ] Use switching logic when failing over
- [ ] Use exponential backoff for failover on timeout

**Comment by VocalZero** [comment]
Would be interested in this function since we have multiple servers ourselves. Would it be possible that you implement the function soon or is there already a plan when it will be added?

**Comment by eshaz** [comment]
Thanks for letting me know you're interested. I'll plan on adding this to the next feature release.
