### ISSUE TITLE
Please keep updated versions published

### ISSUE THREAD

**Issue by karolyi** [eshaz/icecast-metadata-js#160]
Hey,

according to https://www.npmjs.com/package/icecast-metadata-player, you haven't published V1.2 on it.

Could you please keep that updated as well? I don't want to have to specify a github repo url in my package.json.

Thanks!

**Comment by eshaz** [comment]
I think you may have been confusing `icecast-metadata-player` with `icecast-metadata-js`, which are two different libraries. You should not try to customize what version of `icecast-metadata-js` you are using in your project, and just use the version that's specified in dependencies of `icecast-metadata-player`. Trying to pull in a different version is not supported and will probably result in issues, if it even works at all.

I have updated all of the dependencies for all of the libraries in this repo so `icecast-metadata-player` and `icecast-metadata-stats` will pull in the latest `icecast-metadata-js`.

**Comment by karolyi** [comment]
Hey,

you probably missed the information that both the repo and homepage link on https://www.npmjs.com/package/icecast-metadata-player points to this repository. Hence why I was comparing version numbers with this repo.

Updating that will eliminate future issues like this.
