### ISSUE TITLE
How to update Now playing using switchEndpoint?

### ISSUE THREAD

**Issue by EvgeniyDoctor** [eshaz/icecast-metadata-js#168]
I want to make a big amount of radio stations (more than 10) and i do not want to create 10 instances of the player for every endpoint.
Here is my switchEndpoint:
```
<button onclick="player.play();">Play</button>
<button onclick="player.stop();">Stop</button>
	
<button onclick="player.switchEndpoint('http://ip:port/name.ogg', {})">Switch</button>
	
<p>Now Playing: <span id="metadata"></span></p>
```
Now 'Now playing' updates only when new track is started on the switched station or i have to press Stop and then Play. Callbacks are not allowed for switchEndpoint. How?

**Comment by eshaz** [comment]
The metadata should update as soon as the new endpoint starts playing. I'll take a look at that, and try to reproduce it.

Are these multiple stations with the same source, i.e. same audio, or are they separate sources? If they are separate, I would recommend creating a new instance for each of them. You can reference the demo page for examples.

While the `switchEndpoint` method might work for endpoints with different audio sources, it's meant to change the stream endpoint in cases where the underlying audio source is the same, i.e. different codecs, bitrates, or load balanced streams. It performs a few syncing operations that enables a gapless switch between two endpoint of the same audio source.

**Comment by EvgeniyDoctor** [comment]
```
<script>
	function metadataUpdate(metadata){
		console.log(metadata)
		document.getElementById("metadata").innerHTML = metadata.ARTIST + " - " + metadata.TITLE;
	}
	//----
	
	const player = new IcecastMetadataPlayer("http://192.168.0.213:8000/trance.ogg", {
		onMetadata: metadataUpdate,
		metadataTypes: ["ogg"]
	})
</script>

<main class="px-3">
	<h2 class='title'>Radio</h2>
	
	<button onclick="player.play();">Play</button>
	<button onclick="player.stop();">Stop</button>
	
	<button onclick="player.switchEndpoint('http://192.168.0.213:8000/psy.ogg', {})">Switch</button>
	
	<p>Now Playing: <span id="metadata"></span></p>
</main>
```

This is the full code. When i press 'Switch' i do not see any output in the console and no new data in 'Now playing'.
So, should i create more instances in my case?

**Comment by eshaz** [comment]
Yes, it looks like your two streams are probably different audio sources, so I would recommend creating new instances.
