### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by allquixotic** [eshaz/icecast-metadata-js#171]
On both MacOS and Windows, with no addons or extensions, the minimal HTML demo doesn't work on Firefox. This is true of both the default "isics" stream endpoint that you set up in the demo, as well as my own personal music stream.

Steps to reproduce:

1. Install the latest stable Firefox
2. Go to https://eshaz.github.io/icecast-metadata-js/bare-minimum-demo.html
3. Click Play
4. Observe that no audio ever plays
5. Visit the same webpage on Chrome or Safari
6. Click Play
7. Observe that audio plays

**Comment by allquixotic** [comment]
I tried various player backends - WebAudio, HTML5 and MSE - and none of them work on Firefox. I get script errors in the console, but I can't tell what they are because the code is minified.

**Comment by eshaz** [comment]
Thanks for letting me know. I found a small typo that caused this in the latest release, and will be publishing a patch release to fix it.
