### ISSUE TITLE
DOMException: The play() request was interrupted because the media was removed from the document

### ISSUE THREAD

**Issue by EvgeniyDoctor** [eshaz/icecast-metadata-js#173]
On **linux** (**manjaro** 22.1.2) in **brave browser** (Version 1.51.118 Chromium: 113.0.5672.126 (Official Build) (64-bit)) playback does not work (and in firefox), i get this error:
```
DOMException: The play() request was interrupted because the media was removed from the document.
```

On **windows 10** in the **same browser** of the **same version** everything works well, no errors.
I edited my play function, so now it works sometimes and sometimes it does not; sometimes can play 2 audio streams at the same time (on linux). Before it was `player.play()` only.

```
function playerPlay(){
	var thePromise = player.play()
	if (thePromise != undefined) {
		thePromise.then(function(_) {
			player.stop();
			player.currentTime = 0;
			player.play();
		})
		.catch(error => {
			d("! Error play")
		});
	}
	else {
		player.play()
	}
}
```
On the demo page most of the stations works.

Include:
```
<script src="/static/libs/player/icecast-metadata-player-1.16.1.main.min.js"></script>
<script src="/static/libs/player/icecast-metadata-player-1.16.1.synaudio.min.js"></script>
<script src="/static/libs/player/icecast-metadata-player-1.16.1.mediasource.min.js"></script>
<script src="/static/libs/player/icecast-metadata-player-1.16.1.vorbis.min.js"></script>
<script src="/static/libs/player/icecast-metadata-player-1.16.1.common.min.js"></script>
```

If i go to `ip:port/name.ogg` in the browser, everything works fine.

**Comment by eshaz** [comment]
Can you try this out using the demo page and see if the issue persists?

**Comment by eshaz** [comment]
I won't be able to help much unless I can reproduce the error myself. Do you have a link to your website I can try or a link to your code?

In the meantime, to check if your browser environment is causing this error, can you try playing the streams [here](https://dsmrad.io). Each button on the website represents a unique stream and creates its own instance of IcecastMetadataPlayer when clicked. You should be able to play as many streams simultaneously as you want.

**Comment by EvgeniyDoctor** [comment]
Thank you, but actually, i do not need help anymore. I made all the functionality from scratch by myself without any js lib and it works. Even on iOS. So this issue does not matter for me anymore.

And i tested your link a little bit.
- Des Moines PF: works only All, Interop and Law Dispatch
- Des Moines AF: 0/3 works
- ISICS: works only Law Dispatch
- SARA: All, Interop with frequently scanning
