### ISSUE TITLE
Station name from metadata?

### ISSUE THREAD

**Issue by alariej** [eshaz/icecast-metadata-js#175]
Sorry if I'm missing the obvious, but is there a way to retrieve the official station name from the stream metadata? Or is there an API call specifically for that?

Thanks for the great library. I'm using it in a small vite+react+electron project and it works perfectly.

**Comment by eshaz** [comment]
You can use the [`icecast-metadata-stats`](https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-stats#ogg-metadata) library for this. There are a few API calls that provide this information, depending on if you are using Icecast or Shoutcast. You can try these out in the [demo](https://eshaz.github.io/icecast-metadata-js/demo.html#icecast-metadata-stats) with your station to see which one works for you.

**Comment by alariej** [comment]
Many thanks, exactly what I was looking for :-)
