### ISSUE TITLE
webaudio analyser ?

### ISSUE THREAD

**Issue by 808y** [eshaz/icecast-metadata-js#178]
hi there!
i'm trying to get an icecast stream analysed with webaudio (pitch detection)
but i cannot get it working 
        audioContext = new AudioContext();
        analyser = audioContext.createAnalyser();
        analyser.fftSize = 2048;
	sourceNode = audioContext.createMediaStreamSource(audioElement);
        sourceNode.connect( analyser );

got a 'TypeError: this.xi.createMediaStreamDestination is not a function'

how should i declare audioElement ?

**Comment by 808y** [comment]
OK thanks for your answer
i'll try mediasource (makes sense to use that method)
i used webaudio as playback method for IcecastMetadataPlayer ...

so now it works!

`	analyser = audioContext.createAnalyser();
	analyser.fftSize = 2048;
	const source  = audioContext.createMediaElementSource(player.audioElement);
	source.connect( analyser );
	analyser.connect( audioContext.destination );		
	updatePitch();
`

**Comment by eshaz** [comment]
Awesome, glad it's working for you!
