### ISSUE TITLE
Authenticated streams not working?

### ISSUE THREAD

**Issue by SIneyq** [eshaz/icecast-metadata-js#183]
great work, but it seems it cannot handle icecast streams with authentication , eg, something like https://user:password@some.stream/url . Unfortunately my javascript skills are not good enough to determine , if the problem is in icecast-metadata or some underlying code/libs. Or am I completely wrong / too stupid ?

**Comment by eshaz** [comment]
I've never tested this with an authenticated stream, but it should work with a small change. For basic auth, i.e. user and password authentication, you will need to [set the `Authorization` header in the request](https://stackoverflow.com/a/51500400). Right now, there's no way for a consumer of this library to do that, but I can add that feature in.

Just to be sure, can you post the error you recieved when trying this?

**Comment by SIneyq** [comment]
I would have posted the error message, but did not get any. Neither in some log files nor in the javascript console. Would be nice, if you add that feature to set the auth header. I tried some example code like this:
const player1 = 
    new IcecastMetadataPlayer(
      "https://some.stream/sb",
      { onMetadata }
    );

which works perfectly. But with this:

const player1 = 
    new IcecastMetadataPlayer(
      "https://user:password@some.stream/sb",
      { onMetadata }
    );
I don't get any anything, not even an error message somewhere.

**Comment by SIneyq** [comment]
Isn't it the underlying Media Source Extensions lib, that should interpret the user:password parameters and send appropriate auth headers ?

**Comment by eshaz** [comment]
I've released 1.17.0 that adds a feature to allow you to authenticate.

You can supply the user and password using the new `authentication` option noted [here](https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-player#options).

Also, you will need to make sure your Icecast server or your proxy is adding `Authorization` to the `Access-Control-Allow-Headers` header when it responds to the `OPTIONS` response for CORS.

Read here for more info on [CORS](https://github.com/eshaz/icecast-metadata-js/tree/master#cors).
