### ISSUE TITLE
CORS or header problem from icecast2

### ISSUE THREAD

**Issue by wartinw** [eshaz/icecast-metadata-js#184]
Hello. I'm trying to make this excelent library work with my icecast2 stream. I'm using icecast2 2.4.4 in debian 12. When writing my stream URL from your demo page it says 'TypeError'.
I downloaded icecast-metadata-js and tried to run it from the same domain. Looking for the headers there is an OPTIONS request that gives me 'CORS Failed'.  After that, there is a GET with "NS_ERROR_DOM_BAD_URI".

I've read almost everything I found in forums. I tried the headers you wrote somewhere else in icecast.xml:
```
        <header type="cors" name="Access-Control-Allow-Origin" value="*" />
	<header type="cors" name="Access-Control-Allow-Methods" value="GET, OPTIONS" />
	<header type="cors" name="Access-Control-Allow-Headers" value="Content-Type, Icy-Metadata" />
	<header type="cors" name="Access-Control-Expose-Headers" value="Icy-MetaInt, Icy-Br, Icy-Description, Icy-Genre, Icy-Name, Ice-Audio-Info, Icy-Url, Icy-Sr, Icy-Vbr, Icy-Pub" />  
```

tried erasing type="cors" as seen somewhere else.

If I just use from terminal
curl -v 'https://mydomain:8443/mymount' -X OPTIONS
I get "* Empty reply from server"

then I tried another version of icecast2, icecast2-kh from https://www.deb-multimedia.org/pool/main/i/icecast2-dmo/icecast2-dmo
in the icecast.xml provided there is no  <http-headers> section, so I tried commenting out.. without luck.

In some other place I read that in icecast2 2.5 it does reply to a OPTIONS request. 

Sorry to write here, as it's likely an icecast problem. Thank you.

**Comment by wartinw** [comment]
Thanks for your reply!. In the docs you linked it says:
"Avoid placing comments inside http-headers as, in this release, it will prevent Icecast from parsing further header tags."

I'm sure I was commenting before inside headers... BUT, now I'm not but I don't have response if I use curl -x OPTIONS:
`curl: (52) Empty reply from server`

if I use just curl -v, without -x OPTIONS:

```
< HTTP/1.0 200 OK 
< Server: Icecast 2.4.4
< Connection: Close
< Date: Thu, 28 Sep 2023 23:48:09 GMT
< Content-Type: audio/mpeg
< Cache-Control: no-cache, no-store
< Expires: Mon, 26 Jul 1997 05:00:00 GMT
< Pragma: no-cache
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: Icy-Metadata
< Access-Control-Allow-Methods: GET, OPTIONS
< Access-Control-Expose-Headers: Icy-MetaInt, Icy-Br, Icy-Description, Icy-Genre, Icy-Name, Ice-Audio-Info, Icy-Url, Icy-Sr, Icy-Vbr, Icy-Pub
< icy-br:128
< ice-audio-info: bitrate=128
< icy-description:The description
< icy-genre:Genre
< icy-name:Name
< icy-pub:0
< icy-url:http://localhost/
< 
```

Maybe I should try using icecast behind my apache server like you do with Nginx, as this is quite frustrating.

Thanks again!

**Comment by blantonl** [comment]
Here is a working example of using haproxy v2.2 in front of icecast to provide SSL and the necessary CORS headers for this library to work.  

```
global
    log        localhost local0 err
    maxconn    1000000
    user haproxy
    group haproxy
    chroot     /var/empty
    pidfile    /var/run/haproxy.pid
    daemon
    quiet

    tune.ssl.cachesize 1000000
    ssl-default-bind-options no-sslv3 no-tlsv10
    ssl-default-bind-ciphers ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    ssl-default-server-options no-sslv3 no-tlsv10
    ssl-default-server-ciphers ECDH+AESGCM:ECDH+CHACHA20:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
    tune.ssl.default-dh-param 2048

defaults
    log  global
    maxconn 250000


frontend https-in
    bind       :443 ssl crt /your/ssl/cert/chain.pem
    mode       http

    acl is_options method OPTIONS
    use_backend cors_backend if is_options

    http-request set-header X-Forwarded-Proto https
    default_backend icecast

backend cors_backend
    mode http
    http-after-response set-header Access-Control-Allow-Origin "*"
    http-after-response set-header Access-Control-Allow-Methods "GET,OPTIONS"
    http-after-response set-header Access-Control-Allow-Headers "Icy-Metadata"
    http-request return status 204


backend icecast
    mode http
    balance roundrobin
    maxconn 1000000
    http-response add-header Access-Control-Allow-Origin "*"
    http-response add-header Access-Control-Allow-Methods "GET"
    http-response add-header Access-Control-Allow-Headers "Icy-Metadata"
    http-response add-header Access-Control-Expose-Headers "Icy-MetaInt,Icy-Br,Icy-Description,Icy-Genre,Icy-Name,Ice-Audio-Info,Icy-Url"
    server icecast1 127.0.0.1:8080 maxconn 1000000
```
