### ISSUE TITLE
Uncaught ReferenceError: player is not defined

### ISSUE THREAD

**Issue by onenures** [eshaz/icecast-metadata-js#190]
Hello. Thanks for your player. I have configured icecast2 with ices2 to play a stream in ogg format. The problem is that the ogg format is not understood by iOS and playback does not work in a regular HTML5 player.

So I tried your solution. But there was a problem when installing the player. I uploaded the **icecast-metadata-player-1.17.1.main.min.js** file to the desired directory on the server, and it is visible in the site code. And then added the following code to the HEAD tag (this is the code from your example):

```
<script>
   const onMetadata = (metadata) => {
     document.getElementById("metadata").innerHTML = metadata.StreamTitle;
   };
   const player =
     new IcecastMetadataPlayer(
       "https://site.com:8443/radio.ogg",
       {onMetadata}
     );
</script>
```

B outputted the button code also shown in your example:

```
<div>
<button onclick="player.play();">Play </button>
<button onclick="player.stop();"> Stop </button>
</div>
```

The problem is that the browser debugger throws an error "Uncaught ReferenceError: player is not defined at HTMLButtonElement.onclick" which I don't understand how to fix. Yes, I also have jquery.min.js?ver=3.7.0 loaded, so I don't think the problem is loading the jQuery library.

**Comment by eshaz** [comment]
There are a few things missing from the description of your code. Please try the steps outlined [here](https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-player#install-as-a-standalone-script) to install it as a standalone script. Let me know if that works.

**Comment by onenures** [comment]
Unfortunately, I'm new to JavaScript. All I understand is that the error "Uncaught ReferenceError: IcecastMetadataPlayer is not defined" appears because the **IcecastMetadataPlayer** constant is not declared. I copied the following code onto the page and still get this error:

```
<script src="icecast-metadata-player-1.17.1.main.min.js"></script>
<script>
  const onMetadata = (metadata) => {
    document.getElementById("metadata").innerHTML = metadata.StreamTitle;
  };
  const player = 
    new IcecastMetadataPlayer(
      "https://dsmrad.io/stream/isics-all",
      { onMetadata }
    );
</script>
<div>
  <button onclick="player.play();"> Play </button>
  <button onclick="player.stop();"> Stop </button>
  <p> Now Playing: <span id="metadata"></span> </p>
</div>
```

**Comment by eshaz** [comment]
You will need to copy all of the js files in the build folder to the same path that you have the main script and make sure the browser is able to download those assets as needed. If you follow the steps in the docs, it should work for you.

**Comment by onenures** [comment]
All the scripts from here are in one folder (CMOD 755). I also have the correct path to **icecast-metadata-player-1.17.1.main.min.js** registered, it is visible in the page code. I even tried connect **icecast-metadata-player-1.17.1.vorbis.min.js**, also specifying it as:

`<script src="/wp-content/icecast-metadata-player/icecast-metadata-player-1.17.1.vorbis.min.js"></script>`

Should additional scripts that are located in the directory be displayed in the page code in the browser?

There is also another error in the browser debugger in **icecast-metadata-player-1.17.1.main.min.js**:

`Uncaught SyntaxError: Unexpected token '<'.`

![uncaught](https://github.com/eshaz/icecast-metadata-js/assets/150121719/5cfb56cf-1cdc-4179-b51a-8da3ec8bb42b)

**Comment by eshaz** [comment]
Can you inspect the response for that error? I bet you are getting HTML back instead if the script, probably because the path to your script doesn't match where it is stored on your hosting provider.

I'm not a word press expert, but maybe there's some configuration you need to do there as well.

**Comment by onenures** [comment]
Thanks for the answer. He helped me find the problem. It helped to completely save the script in the **icecast-metadata-js-master** folder. At the moment, there are no errors mentioned above. But now I am getting another error similar to here #https://stackoverflow.com/questions/76084843/icecast-server-for-icecast-metadata-player 

> GET https://IP:PORT/mount net::ERR_EMPTY_RESPONSE

Everything works in a simple HTML player:

`<audio src="https://site.com:8443/radio.ogg" controls></audio>`

**Comment by onenures** [comment]
After fixing CORPS, the player worked on Windows and Android. But it doesn't work on iOS. I tested this on an iPad (iOS 12.5.7) and iPhone 7 (iOS 16.5.1). Do I understand correctly that in the following configuration the player should play OGG on iOS 12.4 and higher?

```
<script src="/wp-content/plugins/icecast-metadata-js-master/src/icecast-metadata-player/build/icecast-metadata-player-1.17.1.main.min.js"></script>
<script>
  const onMetadata = (metadata) => {
    document.getElementById("metadata").innerHTML = metadata.StreamTitle;
  };
const player = new IcecastMetadataPlayer("https://site.com:9030/radio.ogg", { 
   onMetadata: (metadata) => { console.log(metadata); },   
   metadataTypes: ["ogg"], 
}
    );
</script>
<div>
  <button onclick="player.play();"> Play </button>
  <button onclick="player.stop();"> Stop </button>
</div>
```

**Comment by onenures** [comment]
Found the problem. This is amazing. I changed the mount point from "radio.ogg" to "radio". Once again, thank you very much for your help and the player, it plays without delay when you click on Play.
