### ISSUE TITLE
Audio stops playing after 5 seconds.

### ISSUE THREAD

**Issue by realmajed** [eshaz/icecast-metadata-js#198]
Hello, I'm trying to figure out why the Audio stops at around 5.20 or 5.30. I do not own the station/stream.
I did disable ICY as I kept getting these errors.
![image](https://github.com/eshaz/icecast-metadata-js/assets/67005991/5381593e-ab3a-4db3-91cf-fc35f737e9a2)

Radio Link: https://21363.live.streamtheworld.com:443/SMOOTHRELAX_SYD_AAC.aac

![image](https://github.com/eshaz/icecast-metadata-js/assets/67005991/bdba3fad-bf4c-49d6-9407-0353a19398bb)

Natively playing the audio using [HTMLAudioElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio) does work with no issues.

**Comment by eshaz** [comment]
Which browser platform are you using? Do you get any errors when the audio stops? You might take a look at the network tab, if debugging on a desktop, and check if the request is still ongoing.

**Comment by realmajed** [comment]
Using Chromium/Chrome based browser, no the request stops.

Ah I just figured it out by cross referencing the headers from, using [**new Audio()**](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio) and using the [Ice Cast Demo](https://eshaz.github.io/icecast-metadata-js/demo.html). It seems to be requesting the first 5 seconds only because this Request header is missing. **Range: bytes=0-** 

After using a network request modifier on Chrome, I was able to listen to the stream without interruptions. Is it possible to somehow include that Header?

**Comment by eshaz** [comment]
Good find. I can probably just hard code that into the library, since I don't think there would be any harm in adding that by default.

Otherwise, I would need to add a new constructor property to be able to set custom headers, which could be used to supply the header to the request.

I'll take a look at adding these in.

**Comment by eshaz** [comment]
I've released version [`1.17.3`](https://github.com/eshaz/icecast-metadata-js/releases/tag/icecast-metadata-player%2F1.17.3) that fixes this issue by hard coding the range value in the request. I don't think there's a scenario where this will cause problems, but if does please let me know.
