### ISSUE TITLE
Poorly formatted scripts?

### ISSUE THREAD

**Issue by shibowo** [eshaz/icecast-metadata-js#203]
As I was trying to install the standalone(non-nodejs) scipts for Icecast Metadata Player I noticed they were all [formatted in one line](https://github.com/eshaz/icecast-metadata-js/blob/15cf791f30b4eb99f4beeebe2dec65c9154f2232/src/icecast-metadata-player/build/icecast-metadata-player-1.17.3.common.min.js#L21) for some reason. This makes it extremely hard to read. Was this intentional? Or an accident?

I like to read the code that I am planning to use before I use it, plus it would be a lot more maintainable if formatted.

**Comment by Yahav** [comment]
That would be the already built/compiled code, look at the src folder for the sources...

**Comment by shibowo** [comment]
Compiled? It's javascript...not a compiled language. Neither is the source written in some language that compiles down to js...

**Comment by Yahav** [comment]
So lets call it bundled ok?
It is a bundled, minified source code.
Once again, look at the src folder for the actual source.

**Comment by shibowo** [comment]
My bad. Thanks for explaining what's going on!
