### ISSUE TITLE
NotAllowedError on Safari 16 after interacting with the page

### ISSUE THREAD

**Issue by pieterdd** [eshaz/icecast-metadata-js#209]
This might be out of your control, so I'm not sure I'm in the right place. I'm often getting the following error on Safari versions lower than 16 when manually starting playback with a mouse click:

> Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

![image](https://github.com/user-attachments/assets/a3446611-d374-494e-a56f-529f8aa6a9dd)

I'm guessing I somehow triggered the Safari measure that guards against unwanted autoplaying audio, as mentioned in the [README](https://github.com/eshaz/icecast-metadata-js/tree/main/src/icecast-metadata-player#error-messages). Playing Groove Salad through https://eshaz.github.io/icecast-metadata-js/ works just fine in my test environment. So does this:

```html
<script src="https://eshaz.github.io/icecast-metadata-js/icecast-metadata-player-1.17.9.main.min.js"></script>
<script>
const player = new IcecastMetadataPlayer("https://ice4.somafm.com/groovesalad-64-aac", {
  onMetadata: (data) => {
  	document.querySelector('#metadata').innerHTML = data.StreamTitle;
  },
});
</script>
<div id="metadata">
metadata goes here
</div>
<button onclick="player.play()">
Play
</button>
```

I saw the [guide](https://developer.mozilla.org/en-US/docs/Web/Media/Autoplay_guide) you linked to, specifically this (emphasis mine):

> As a general rule, you can assume that media will be allowed to autoplay only if **at least one of the following** is true:
> 
> - The audio is muted or its volume is set to 0
> - The user **has interacted with the site** (by clicking, tapping, pressing keys, etc.)
> - If the site has been allowlisted; this may happen either automatically if the browser determines that the user engages with media frequently, or manually through preferences or other user interface features
> - If the autoplay [Permissions Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy) is used to grant autoplay support to an [<iframe>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) and its document.

On Safari 17, playback of Groove Salad consistently works fine for me:

![image](https://github.com/user-attachments/assets/e292a03b-acd9-419d-9b59-addc35d83f0a)

Any guesses as to why this error might be triggering even after having interacting with the page before starting playback?

Don't worry if you don't - I can't expect you to debug an external website. I should probably narrow it down to a minimal reproduction scenario. But if you happen to have any documentation on Safari 16's audio policies I haven't unearthed yet, feel free to pass them along.

**Comment by eshaz** [comment]
I don't know anything specific for Safari 16, but I do have a few workarounds in place for this issue. If memory serves correctly, these are all for Safari / iOS based browsers. Chrome / Firefox / Edge / Android all are less restrictive, or at least better implemented to recognize that the user actually did interact with the page to play audio.

* For WebAudio playback, I have an event listener hooked up to `window.document` for clicks / touch events that happen anywhere on the webpage to start the AudioContext. If this doesn't work, there should be an error logged to the console.
https://github.com/eshaz/icecast-metadata-js/blob/4abb117be77dfbf6a1e73596b7f97261ffb9691f/src/icecast-metadata-player/src/IcecastMetadataPlayer.js#L604-L651

* For the most recent issue we had in #206, the Audio element is configured to play silence after `play()` is called so it can be triggered immediately and directly by a user action. When the HTTP request starts to return audio data, the Audio element `src` attribute is updated to play the stream audio. The `play()` method must be called from a user initiated event for this to work.
https://github.com/eshaz/icecast-metadata-js/blob/4abb117be77dfbf6a1e73596b7f97261ffb9691f/src/icecast-metadata-player/src/IcecastMetadataPlayer.js#L401-L405

I would be curious to see where the exception is being thrown from in IcecastMetadataPlayer. You should be able to compile your webpage with source maps to get a better stack trace. This might give some hints to what could be happening. However, just guessing, maybe two things could be happening:

* If the player is being interacted with inside an iframe, shadow DOM, or in some context that doesn't trigger initial click event on `window.document`, then it would stop the WebAudio playback method from working. This would prevent mp3, opus, flac, vorbis from playing in iOS / Safari, but aac might still work.
* Or, if `play()` is being called asynchronously, or not directly from a user action, such as a button click event, then it might prevent the audio element from playing the initial silence.

**Comment by pieterdd** [comment]
Turns out I was confounding variables. The behavior is as follows:

- When I first go to the homepage of the player and start a station, it always works fine with and without sourcemaps. A page navigation happens in this scenario (a fake one, it's a single-page application with a router).
- When I go straight to the page of a specific station and start that station, it consistently triggers the issue on Safari 15. A page navigation does not happen in this scenario.

So I was also able to get the stack trace:
![image](https://github.com/user-attachments/assets/7bf6e1de-6292-457d-a44f-e54b7cf948aa)

The Svelte file is doing the `player.play()` call. The stack trace implies this piece of code got triggered asynchronously. That aligns with how the code works (player init happens as a response to variable changes). So I think one of your hypotheses applies:

> Or, if play() is being called asynchronously, or not directly from a user action, such as a button click event, then it might prevent the audio element from playing the initial silence.

What I can't yet explain, however, is why it does work in other circumstances. The player initialization is always triggered in response to variable changes. So I'd assume that playback always starts asynchronously.

Anyway, this is very likely to be outside your control. Thanks for letting me pick your brain Ethan!

**Comment by eshaz** [comment]
Glad to help! If you do find the issue, would you mind sharing it here? That would help others in the future if they also encounter this.

**Comment by pieterdd** [comment]
Will do! Might turn out to be a good addendum to the Troubleshooting section.

**Comment by pieterdd** [comment]
I put a console log and a `console.trace()` right  before the code calls `player.play()`. Here's the scenario where playback works on Safari 15:

![Screenshot From 2024-12-21 23-19-02](https://github.com/user-attachments/assets/aee0686f-331a-4e20-bdd1-75e569214a0d)

Here's the scenario where it's blocked:

![Screenshot From 2024-12-21 23-19-16](https://github.com/user-attachments/assets/3faa08fd-1e0c-489d-80ba-a13c736c2ed6)

If the reason for getting blocked is related to the play call being async, then I assume the rule is more specific than this. My next step will be to try some async calls in a minimal example.

**Comment by pieterdd** [comment]
This plays without issue in Safari 15:

```html
<script src="https://eshaz.github.io/icecast-metadata-js/icecast-metadata-player-1.17.9.main.min.js"></script>
<script>
const player = new IcecastMetadataPlayer("https://ice4.somafm.com/groovesalad-64-aac", {
  onMetadata: (data) => {
  	document.querySelector('#metadata').innerHTML = data.StreamTitle;
  },
});

async function start() {
	await new Promise((resolve) => {
  	setTimeout(player.play(), 2000);
  })
}
</script>
<div id="metadata">
metadata goes here
</div>
<button onclick="start()">
Play
</button>
```

So even with timeouts as high as 2000 milliseconds wrapped in a Promise, Safari was happy to oblige:

![image](https://github.com/user-attachments/assets/c1bc7774-8545-46b3-84ac-8ba4eaac41cb)

Based on that, I'm currently under the assumption that the async nature of the call is not what triggered the problem.
