### ISSUE TITLE
Two players on a page

### ISSUE THREAD

**Issue by softshape** [eshaz/icecast-metadata-js#53]
I'm having trouble to put two audio players on a single page. No example nor docs provide info for this case. Can anyone share a correct example of IcecastMetadataPlayer() init when there are audio1 and audio2 elements on a page ? I tried:

```
    const audioElement1 = document.getElementById("audio1");
    icecastMetadataPlayerEng = new IcecastMetadataPlayer("https://dsmrad.io/stream/isics-all", audioElement: audioElement1);

```

but this won't work.

**Comment by eshaz** [comment]
You should just be able to instantiate one or more players, but each player must have it's own audio element. By default, the IcecastMetadataPlayer will create it's own Audio() element.

```
const player_1 = new IcecastMetadataPlayer("https://dsmrad.io/stream/isics-all");
const player_2 = new IcecastMetadataPlayer("https://streaming211.radionomy.com/Jazz4ever");

const playButton = document.getElementById('play');
playButton.addEventListener('click', () => {
  player_1.play();
  player_2.play();
});
```

**Comment by eshaz** [comment]
Let me know if this didn't work for you. I was able to run two players at once using the example above without any issues in Chrome and Firefox.
