### ISSUE TITLE
"aac" station wont play!

### ISSUE THREAD

**Issue by lexterror** [eshaz/icecast-metadata-js#69]
Hi, there is a really good station but it wont play. I just wanted to know if I could play it, and if not why.

 https://streams.radio.co/se1a320b47/listen

Thank you!

**Comment by eshaz** [comment]
The response from this server doesn't allow the `Icy-Metadata` header to be sent cross-origin. Here's what the server responds with on the `OPTIONS` method (copied from the Firefox network tab).
```
HTTP/1.1 200 OK
Connection: Keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, Accept, X-Requested-With, Content-Type
Access-Control-Allow-Methods: GET, OPTIONS, HEAD, STATS
```
Please read about CORS here for more info: https://github.com/eshaz/icecast-metadata-js#cors

I would suggest you check your browser's network tab yourself for the information above before opening another CORS issue.

Unless you can update this server's CORS configuration, there's nothing that can be done to show ICY metadata from this server in a cross-origin request.

Also, not relevant to the issue, but this is stream is not AAC, it's MP3. You can verify this yourself by opening the [HTML demo](https://eshaz.github.io/icecast-metadata-js/demo.html) in Firefox, entering the stream url, uncheck `ICY`, and click play. The following codec information will show up on the right indicating this is MPEG Version 1 Layer III (i.e. MP3)

```
bitDepth | 16
bitrate | 192
channelMode | Joint stereo
channels | 2
emphasis | none
framePadding | 1
isCopyrighted | false
isOriginal | true
isPrivate | false
layer | Layer III
modeExtension | Intensity stereo off, MS stereo on
mpegVersion | MPEG Version 1 (ISO/IEC 11172-3)
protection | none
sampleRate | 44100
```
