### ISSUE TITLE
readme stop() example

### ISSUE THREAD

**Issue by JustinWebDev** [eshaz/icecast-metadata-js#70]
In https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-stats#usage, there is
To start querying once every n seconds for metadata and statistics, call start().
statsListener.start();

To stop querying, call stop()
statsListener.start();

Why does the stop() example have .start()?

**Comment by eshaz** [comment]
That's a typo in the documentation. Thanks for letting me know about it.
