### ISSUE TITLE
onMetadataFailed Support!

### ISSUE THREAD

**Issue by lexterror** [eshaz/icecast-metadata-js#78]
Hi, Im trying to get feedback after calling onMetadataFailed! Does it work for the metadata only? And not the entire Stream?

Thank you!

**Comment by eshaz** [comment]
`onMetadataFailed` is only called when ICY or Ogg metadata failed to be detected. See the link below for more information. This event assumes the stream connection was successful. It can only happen after the stream successfully connects and starts to return data.

https://github.com/eshaz/icecast-metadata-js/tree/master/src/icecast-metadata-js#callbacks

**Comment by lexterror** [comment]
Thank you!

**Comment by lexterror** [comment]
Hi eshaz!

I was able to get it working! Thank you for pointing out that it checks after it starts playing the stream!

I have a demo of my player here:

http://elounge.org

Thank you!
