### ISSUE TITLE
EROR connection/_handle_connection HTTP request parsing failed

### ISSUE THREAD

**Issue by edier88** [eshaz/icecast-metadata-js#79]
Hi. I hope you're ok. I've been testing my streaming with the "Bare Minimum HTML Demo" but the only response I get is this blocking responses from my server. Maybe I'm missing something in the icecast.xml ??

![image](https://user-images.githubusercontent.com/60574389/135690165-3919ada9-3d9a-4020-97d2-b76c2b6176be.png)

I have also looked at the logs, specifically /var/log/icecast/error.log
After taking a look at it I find that there's an error in the parsing (EROR connection/_handle_connection):

```
[2021-10-01  16:51:59] DBUG stats/modify_node_event update global clients (0)
[2021-10-01  16:51:59] DBUG stats/modify_node_event update global clients (1)
[2021-10-01  16:51:59] DBUG stats/modify_node_event update global connections (59)
[2021-10-01  16:51:59] DBUG stats/modify_node_event update global clients (0)
[2021-10-01  16:51:59] DBUG stats/modify_node_event update global clients (1)
[2021-10-01  16:51:59] DBUG stats/modify_node_event update global connections (60)
[2021-10-01  16:51:59] DBUG stats/modify_node_event update global clients (0)
[2021-10-01  16:51:59] EROR connection/_handle_connection HTTP request parsing failed
[2021-10-01  16:51:59] EROR connection/_handle_connection HTTP request parsing failed
[2021-10-01  16:51:59] EROR connection/_handle_connection HTTP request parsing failed
```

Is it something in the icecast.xml, I don't know if I'm missing some permissions, have you come across this problem before?
Thanks for your piece of software. I would like to use it like a charm. If you know something let me know please.

**Comment by eshaz** [comment]
Hi, there are a few common things that can go wrong. Could you take a look at the [troubleshooting steps](https://github.com/eshaz/icecast-metadata-js#troubleshooting-1) and see if any of these help?

I've never seen that error before in Icecast. If you can play the stream in something like VLC, or just by pasting the URL in your browser, I would think that should rule out any icecast.xml parsing issues.

You should see more details on the error by clicking on the network request in your browser console. Could you post a screenshot of that for one of the failing requests?

**Comment by edier88** [comment]
Hi, I appreciate too much your fast response, I want to apologise for my late one.
It turned out to be a CORS problem, I'm using Icecast 2.4.4
What I did is to set the headers you described in your [troubleshooting steps](https://github.com/eshaz/icecast-metadata-js#troubleshooting-1) in the icecast.xml, just after the **_listen-socket_** tags. This way:
```
<http-headers>
    <header name="Access-Control-Allow-Origin" value="*" />
    <header name="Access-Control-Allow-Methods" value="GET,OPTIONS" />
    <header name="Access-Control-Allow-Headers" value="Content-Type,Icy-Metadata" />
    <header name="Access-Control-Expose-Headers" value="Icy-MetaInt,Icy-Br,Icy-Description,Icy-Genre,Icy-Name,Ice-Audio-Info,Icy-Url,Icy-Sr,Icy-Vbr,Icy-Pub" />
</http-headers>
```
I also set the "metadataTypes" to "ogg":

```
const getIcecastMetadataPlayer = () => {
      icecastMetadataPlayer = new IcecastMetadataPlayer(endpoint.value, {
        audioElement,
        onMetadata,
        onMetadataEnqueue,
        metadataTypes: ["ogg"],
        icyDetectionTimeout: 5000,
        enableLogging: true,
        onError: (message) => {
          metadataEl.innerHTML = message;
        },
      });
    };
```
I want to thank you for the great library. Keep it that way!

**Comment by eshaz** [comment]
Glad you figured it out!
