### ISSUE TITLE
Metadata: Character decoding issues

### ISSUE THREAD

**Issue by BajakiGabesz** [eshaz/icecast-metadata-js#85]
First of all: thanks for your life-safer library, it really helps me a lot.

Anyway, I found an issue that may have an easy workaround:
Some Icecast versions could send different kinds of character sets than UTF-8 which could happen because of the source of the stream or the Icecast configuration. It makes it harder to decode some Central-European or other kinds of characters, for example in our case the character set is ISO-8859-2, but when the MetadataParser decoding the metadata, [it's forced to read it as UTF-8](
https://github.com/eshaz/icecast-metadata-js/blob/4c4c687b56784352a940e30f361e6b8e1e1f078c/src/icecast-metadata-js/src/MetadataParser/MetadataParser.js#L35).
As I see it's possible to add a new parameter to be able to set the decoder charset.
In this case, the IcecastMetadataPlayer can be configurable to be able to show accents and other characters properly for other languages as well. By default, it could stay as it is and it should be available to set it up by a parameter in the IcecastMetadataPlayer constructor.

What do you think about it? Do you have another workaround or is it easy to handle as I described?

Thanks for your help!

**Comment by eshaz** [comment]
I think that's a great idea. Also, thanks for the detailed information about the issue, that's very helpful. I'll see if I can get a new parameter in to override the `utf-8` encoding this weekend.

Do you have a stream I can connect to that uses this character encoding?

**Comment by BajakiGabesz** [comment]
That's great news!
Of course, I can share a stream with you. You can find one [here](https://oxygenmusic.hu:8443/oxygenmagyarzene) which mainly contains accents for every music played. Anyhow, you could hear some Hungarian songs as well if you are interested. :)
Thank you for your fast reply, I really appreciate it. Let me know if I could help you with tests this weekend if you have some progress!

**Comment by BajakiGabesz** [comment]
I did some tests and if I change the decoder encoding to ISO-8859-2, then it works properly, I can make a PR from it and you may change it as you would like to.

**Comment by BajakiGabesz** [comment]
I made a PR: #86. Take a look at it and if it's okay then I think it's done.
I tested it with the stream above and everything was working properly.

**Comment by BajakiGabesz** [comment]
Thanks for your fast merge and publish and for the new versions.

**Comment by eshaz** [comment]
@BajakiGabesz I've released `icecast-metadata-player/1.10.0` that contains this feature. When instantiating the player, you can pass in the `icyCharacterEncoding: "iso-8859-2"` in the options parameter to use this character encoding. I tested it with your stream, and it showed the accents properly.
